const types = {
  FETCH_MOVIES_FAILED: "LOADING_MOVIES_FAILED",
  FETCH_MOVIES_SUCCESS: "LOADING_MOVIES_SUCCESS",
  FETCH_MOVIES_PENDING: "FETCH_MOVIES_PENDING",
  GET_MOVIE_DETAILS_PENDING: "GET_MOVIE_DETAILS_PENDING",
  GET_MOVIE_DETAILS_SUCCESS: "GET_MOVIE_DETAILS_SUCCESS",
  GET_MOVIE_DETAILS_FAILED: "GET_MOVIE_DETAILS_FAILED",
  NOMINATE_MOVIE: "NOMINATE_MOVIE",
  REMOVE_NOMINATED_MOVIE: "REMOVE_NOMINATED_MOVIE",
};

export default types;
